name: network_resource
description: Deprecated in favor of async_resource. Automatically cache network resources and use them when offline.
version: 0.2.5
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/network_resource

dependencies:
  http: ^0.11.3+16
  meta: ^1.1.5
  path: ^1.6.1

dev_dependencies:
  mockito: ^3.0.0-beta+3
  test: ^1.3.0

environment:
  sdk: ">=1.19.0 <3.0.0"