name: network_resource
description: Automatically cache network resources and use them when offline.
version: 0.0.1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/network_resource

dependencies:
  flutter:
    sdk: flutter
  path_provider: "^0.4.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <2.0.0"
  flutter: ">=0.1.2 <1.0.0"